# Generated by Django 5.0.1 on 2024-01-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('university', models.CharField(max_length=100)),
                ('exam_date', models.DateField()),
            ],
            options={
                'db_table': 'index',
            },
        ),
    ]
