# Generated by Django 5.0.1 on 2024-01-29 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Details', '0002_rename_name_exam_details_exam_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exam_Details',
            new_name='Exam_Index',
        ),
    ]
