# Generated by Django 5.0.1 on 2024-01-29 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Details', '0003_rename_exam_details_exam_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_description', models.TextField()),
                ('exam_syallabus', models.TextField()),
                ('exam_eligibility', models.TextField()),
                ('exam_official_website', models.URLField()),
                ('exam_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam_Details.exam_index')),
            ],
        ),
    ]
