# Generated by Django 5.0.1 on 2024-01-30 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Details', '0004_exam_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exam_Index',
            new_name='ExamIndex',
        ),
        migrations.CreateModel(
            name='ExamDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=200)),
                ('exam_description', models.TextField()),
                ('exam_syallabus', models.TextField()),
                ('exam_eligibility', models.TextField()),
                ('exam_official_website', models.URLField()),
                ('exam_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam_Details.examindex')),
            ],
        ),
        migrations.DeleteModel(
            name='Exam_Details',
        ),
    ]
