# Generated by Django 5.0.1 on 2024-01-30 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Details', '0005_rename_exam_index_examindex_examdetails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examdetails',
            name='exam_name',
        ),
    ]
