# Generated by Django 5.0.1 on 2024-01-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Details', '0006_remove_examdetails_exam_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='examindex',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield'),
        ),
    ]
