# Generated by Django 5.0.1 on 2024-01-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Details', '0007_examindex_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examindex',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
