# Generated by Django 5.0.1 on 2024-01-30 08:59

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Details', '0011_remove_examindex_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='examindex',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=0, editable=False, populate_from='exam_name', unique=True),
            preserve_default=False,
        ),
    ]
