# Generated by Django 5.0.1 on 2024-01-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Details', '0013_remove_examindex_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='examindex',
            name='slug',
            field=models.SlugField(default=0, help_text='Slug will be generated automatically from the title of the page', max_length=255, unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
