# Generated by Django 5.0.1 on 2024-01-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Details', '0015_alter_examindex_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='examdetails',
            name='courses_offered',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
