# Generated by Django 5.0.1 on 2024-01-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Details', '0016_examdetails_courses_offered'),
    ]

    operations = [
        migrations.AddField(
            model_name='examdetails',
            name='model_papers',
            field=models.FileField(default=0, upload_to='Exam_Details/Model_Papers'),
            preserve_default=False,
        ),
    ]
