# Generated by Django 5.0.1 on 2024-02-04 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Details', '0020_alter_examdetails_model_papers'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='examindex',
            table=None,
        ),
    ]
